### ISSUE TITLE
Invitation 

### ISSUE THREAD

**Issue by devx-opensource** [wearedevx/keystone#23]
Requirements

- Invitee needs a keystone account (in order to have pub keys to use)

Flow:
- Invitee provide a token/code to the project owner
- the project owner uses the code to add him to the project
- the project owner can send an email with the instructions to create an account and generate a code

**Comment by gaelph** [comment]
So, in the data model, there should be another relation between:
- the target projet,
- the invitee user,
- the generated code.

A new line gets added when the invitee generates the code.
Then, the project owner can find the project and user related to said code and proceed with role assignment and so on.

**Comment by gaelph** [comment]
There should be subcommands for each step:
- `ks invite [email]` sends instructions to the invitee to generate the code, and to create a keystone account if necessary
- `ks invite generate [project]` generates an invitee code for the project. The invitee is responsible for transmitting the code
- `ks invite accept [code]` adds the invitee to the project, the project owner assigns their role
- `ks invite reject [code]` discards the project/invitee/code relation

**Comment by devx-opensource** [comment]
Not sure there's a need to link an invitation code to a project. The invitee code could only be used as an identifier to find him on keystone, just like a username. Difference being that it's a one-time use.

* `ks invite [email]` sends instructions to the invitee by email to generate a one-time code (24h TTL) , and to create a keystone account if necessary
* `ks project add [invitee code]` adds the invitee to the project, then the project owner assigns the invitee role

**Comment by gaelph** [comment]
But we  use `ks secret add` to add secrets, and `ks file add` to add files. So `ks project add` looks like it is to add projects.
It looks like we have a new members resource with CRUD operations like secrets and files.

Since in the CLI resources are singular nouns, it gives us:
- `ks member` to list all members of the project with their roles
- `ks member add [codes...]` to add members. Maybe we allow for several codes to be used at once ?
- `ks member rm [usernames...]` to expel members. Same : several usernames at once ?
- `ks member set-role [username]` to set the role  for a member

And:
- `ks invite [emails...]` sends instructions to the invitee by email to generate a one-time code (24h TTL) , and to create a keystone account if necessary
- `ks invite generate-code` to generate the one-time code ?

**Comment by gaelph** [comment]
Would it be possible to add a known list of users from a file ? As in:
`ks member add --from-file the-a-team.yml`

**Comment by gaelph** [comment]
- `ks invite [emails...]` just sends mail with instructions
- `ks whoami` a unique member id of the form <username>@<github|gitlab>

- `ks member add [usernames...]`
